### ISSUE TITLE
poster results

### ISSUE THREAD

**Issue by dbwieland18** [nmunson/rottentomatoes#7]
It looks like each item coming back for "posters" is the same (thumbnail, profile, detailed, original). They all have the same image link, which looks like a thumbnail.

**Comment by nmunson** [comment]
Hey,

It looks like this was a design decision from the Rotten Tomatoes API to stop providing high res images.  See: http://developer.rottentomatoes.com/forum/read/184481.  

"The objective of our program is to provide Rotten Tomatoes scores to enrich movie discovery and not to be a substitute for metadata providers. As such, certain movie metadata (including high-res images) will no longer be provided through the Rotten Tomatoes API but can be obtained from other sources."
