### ISSUE TITLE
Limit restriction

### ISSUE THREAD

**Issue by coreyd303** [nmunson/rottentomatoes#8]
When requesting results from lists i.e. box_office or in_theaters the limit is restricted to 10 or 16 respectively. Even when passing a limit higher than 10 or 16. 

Ex: RottenList.find(:type => "box_office", :limit => 25)  only returns 10 movies, but making a call directly to the API using the browser with the same limit on the same list will return 25 movies.

**Comment by dsully360** [comment]
Hi @coreyd303, did you find a workaround for this? Currently having the same issue.

**Comment by nmunson** [comment]
Hey guys, this should be fixed in 1.1.1 if you want to try it out.  It looks like I never implemented the limit feature in the first place.
