### ISSUE TITLE
Method returns false but is later referenced as an object

### ISSUE THREAD

**Issue by anthonypenner** [nmunson/rottentomatoes#9]
NoMethodError: undefined method `code' for false:FalseClass
    /var/www/istreamguide/shared/bundle/ruby/2.1.0/gems/rottentomatoes-    1.1.0/lib/rottentomatoes/rottentomatoes.rb:47:in `api_call'
    /var/www/istreamguide/shared/bundle/ruby/2.1.0/gems/rottentomatoes-  1.1.0/lib/rottentomatoes/rotten_movie.rb:9:in `find'
    /var/www/istreamguide/releases/20150512234310/app/models/movie.rb:99:in `rotten_api_call'
    /var/www/istreamguide/releases/20150512234310/lib/tasks/data.rake:173:in `block (3 levels) in <top (required)>'
    /var/www/istreamguide/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
    /var/www/istreamguide/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:51:in `each'
    /var/www/istreamguide/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:51:in `block in find_each'
    /var/www/istreamguide/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
    /var/www/istreamguide/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:50:in `find_each'
    /var/www/istreamguide/releases/20150512234310/lib/tasks/data.rake:172:in `block (2 levels) in <top (required)>'

**Comment by anthonypenner** [comment]
I'm trying with line 47 changed to:
`return nil if(response == false || response.code.to_i != 200)`

Might submit a PR later.

**Comment by nmunson** [comment]
Someone's beaten you to the PR, I've merged and made the fix available in v1.1.3.  Thanks for originally reporting the issue.
